apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: kubernetes-cluster-vl1k
  namespace: argocd
  labels:
    take-along-label.capi-to-argocd.foo: ""
    take-along-label.capi-to-argocd.my.domain.com/env: ""
spec:
  rolloutAfter: "2025-08-22T00:00:00Z"
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    class: builtin-generic-v3.3.0
    version: v1.32.3---vmware.1-fips-vkr.2
    variables:
      - name: vmClass
        value: best-effort-xsmall
      - name: storageClass
        value: vks
      - name: osConfiguration
        value:
          trust:
            additionalTrustedCAs:
              - caCert:
                  secretRef:
                    key: harbor01-ca
                    name: ""
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon, content-library=cl-6bc51e04243a8e2eb
    workers:
      machineDeployments:
        - class: node-pool
          name: kubernetes-cluster-vl1k-np-bc1i
          replicas: 3